name: knawat_api
version: 0.0.1
description: Knawat Dart API
homepage: https://github.com/mosamuhana/knawat_api_dart

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  http: ^0.12.2
  equatable: ^1.2.4
  collection: ^1.14.13
